/*
 * AdminMainJFrame.java
 *
 * Created on 16 Aralýk 2006 Cumartesi, 17:22
 */

import admin.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;

/**
 *
 * @author  ozkansari
 */
public class AdminMainJFrame extends JFrame {
    
    /**
     * Creates new form AdminMainJFrame
     */
    public AdminMainJFrame() {
        
        JFrame.setDefaultLookAndFeelDecorated(true);
        
        initComponents();
        
        MenuHandler handler = new MenuHandler(); // create an instance of inner class

        products_Btn.addActionListener(handler);
        update_Btn.addActionListener(handler);
        addProduct_Btn.addActionListener(handler);
        addNewClient_Btn.addActionListener(handler);
        orders_Btn.addActionListener(handler);
        exit_Btn.addActionListener(handler);
        
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        products_Btn = new javax.swing.JButton();
        addProduct_Btn = new javax.swing.JButton();
        orders_Btn = new javax.swing.JButton();
        exit_Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addNewClient_Btn = new javax.swing.JButton();
        update_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ShopApp");
        setLocationByPlatform(true);
        setResizable(false);
        products_Btn.setText("LIST PRODUCTS");
        products_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        addProduct_Btn.setText("ADD NEW PRODUCT");
        addProduct_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        orders_Btn.setText("MANAGE ORDERS");
        orders_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        exit_Btn.setText("EXIT");
        exit_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setBackground(java.awt.Color.pink);
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SPEECH SHOPPING");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(141, 32));

        jLabel2.setBackground(java.awt.Color.lightGray);
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setForeground(java.awt.Color.blue);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIN");
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(141, 40));

        addNewClient_Btn.setText("ADD NEW CLIENT");

        update_Btn.setText("UPDATE PRODUCT");
        update_Btn.setActionCommand("UPDATE PRODUCT");
        update_Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(update_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(products_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addProduct_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addNewClient_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(exit_Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orders_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(26, 26, 26)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(products_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(update_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProduct_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewClient_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orders_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(exit_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        AdminMainJFrame newApp = new AdminMainJFrame();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewClient_Btn;
    private javax.swing.JButton addProduct_Btn;
    private javax.swing.JButton exit_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton orders_Btn;
    private javax.swing.JButton products_Btn;
    private javax.swing.JButton update_Btn;
    // End of variables declaration//GEN-END:variables
    
    /** INNER CLASS FOR MENU EVENT HANDLING
     *
     */
    class MenuHandler implements ActionListener {
        
        public void actionPerformed(ActionEvent event) {
            
            // detect the source of the event generated and perform their respective task
            
            // if 'LIST PRODUCTS' is selected
            if (event.getSource() == products_Btn) {
                ProductListScreen productInventory = new ProductListScreen();
            }
            
            // if 'UPDATE PRODUCT' is selected
            if (event.getSource() == update_Btn) {
                UpdateProductScreen productUpdate = new UpdateProductScreen();
            }
            
            // if 'ADD PRODUCT' is selected
            if (event.getSource() == addProduct_Btn) {
                NewProductForm addNewProductForm = new NewProductForm();
            }
            
            // if 'ADD NEW CLIENT' is selected
            if (event.getSource() == addNewClient_Btn) {
                NewCustomerForm addNewCustomerScreen = new NewCustomerForm();
            }
            
            // if 'MANAGE ORDERS' is selected
            if (event.getSource() == orders_Btn) {
                OrderListScreen orderList = new OrderListScreen();
            }
            
            // if 'EXIT' is selected
            if (event.getSource() == exit_Btn) {
                System.exit(0);
            }
            
        } //--end- actionPerformed() -function--
        
    } // --end-inner-class- "MenuHandler" --
}
